### ISSUE TITLE
Tellprox sensors on linux!

### ISSUE THREAD

**Issue by lugiber** [p3tecracknell/tellprox#1]
I posted this on the Telldus site as well, but i just wanted to let you know.

Just tried this with ubuntu 12.10 and it works great!
Except that i don't get any sensor information. I'm not sure why, i guess that it gets the sensor/light information from tdtool.
This is what i get in the terminal:

```
tdtool --list
SENSORS:

PROTOCOL               MODEL                  ID      TEMP    HUMIDITY   LAST UPDATED       
mandolyn               temperaturehumidity    12      -23.2°   61%        2013-05-02 11:50:40
mandolyn               temperaturehumidity    13      29.2°   29%        2013-05-02 11:51:11
mandolyn               temperaturehumidity    21      7.1°   33%        2013-05-02 08:43:16
mandolyn               temperaturehumidity    14      22.0°   27%        2013-05-02 11:51:20
mandolyn               temperaturehumidity    11      5.0°   63%        2013-05-02 11:51:10
```

But the sensors doesn't show up in the app (Remotestick)

This is the tellprox debug output when trying to access the sensors:

```
cust.bredbandsbolaget.se - - [02/May/2013 11:41:30] "GET /json/sensors/list HTTP/1.1" 200 14
cust.bredbandsbolaget.se - - [02/May/2013 11:41:33] "GET /json/devices/list?supportedMethods=1023 HTTP/1.1" 200 2293
```

And if i visit my site at:

```
my.domain.com:8084/json/sensors/list
```

All i get is this message:

```
{"sensor": []}
```

Any ideas on what could be wrong?
Or how i can debug this further.
Thanks!

/Peter

**Comment by p3tecracknell** [comment]
My mistake, I should have explained in the text describing the project. Essentially I have not implemented sensors yet. As I do not own any, I have moved it down the priority list as it would be harder to implement without the opportunity to test.

I am happy to write the code to the best of my ability if you are happy to test?

**Comment by lugiber** [comment]
Really?
If you would write the code i would be really happy to test it!
Is there anything you'd like me to provide you with before you start?

One thing i have thought of is that it doesn't seem that either telldusd or tdtool keeps any records of the names of the sensors. Eg, it just prints out the the sensor protocol and device id (as you can see in the list).
So it would be a nice feature to be able to name your sensors in the config file. Or a specific sensorfile.
Also, it lists sensors that are not mine (or are caused by some sort of interference)

The complete sensorlist would look something like this:

```
SENSORS:

PROTOCOL                MODEL                   ID      TEMP    HUMIDITY    LAST UPDATED        
mandolyn                temperaturehumidity     12      -23.4° 61%         2013-05-02 17:29:41 
mandolyn                temperaturehumidity     13      28.7°  25%         2013-05-02 17:29:11 
mandolyn                temperaturehumidity     21      20.2°  25%         2013-05-02 17:29:16 
mandolyn                temperaturehumidity     14      21.8°  26%         2013-05-02 17:29:20 
mandolyn                temperaturehumidity     11      4.4°   62%         2013-05-02 16:37:11 
fineoffset              temperaturehumidity     0       0.0°   0%          2013-05-02 17:24:11 
fineoffset              temperaturehumidity     2       0.0°   0%          2013-05-02 14:15:11 
fineoffset              temperaturehumidity     1       0.0°   0%          2013-05-02 16:48:11 
fineoffset              temperaturehumidity     6       0.0°   0%          2013-04-22 15:07:22 
fineoffset              temperaturehumidity     7       -0.0°  0%          2013-04-29 12:20:17 
```

Where the real sensorids are sensors 11,12,13,14,21 and the non existing ones are 0,2,1,6,7.

Hope this helps in some way and thanks for helping out!

**Comment by p3tecracknell** [comment]
What would be great is the format of the information you get back from the API.
If you could go to http://api.telldus.com/ , login and paste in the JSON output from the 4 sensor functions.
Obviously feel free to remove/obfuscate any information, but I could do with seeing the fields in action.
If you spot any information that is coming back differently, that would also be great to know.

In terms of naming information, I will definitely consider that as an enhancement. Hopefully if you go to the root of your address (localhost:8080) you will see my prototype web interface. I plan on allowing the user to add/edit/remove devices, so it makes sense to add sensors in there too.  Would you mind making an enhancement 'issue' so that I can track it please?

**Comment by lugiber** [comment]
I'm on my way from work at the moment. But I'll look at it within 30 minutes! 
Again, thanks for helping out!
