### ISSUE TITLE
Web Root setting does not work

### ISSUE THREAD

**Issue by DonOregano** [p3tecracknell/tellprox#11]
Setting the Web Root value to for example "/tellprox" does not make tellprox run on that adress.
In fact it appears to redirect from http://server/ to http://server/tellprox/devices (which it then says doesnt exist). The url http://server/devices still work.
So it looks like the web root setting is not applied to all URLs.

**Comment by p3tecracknell** [comment]
I never got anywhere with the webroot stuff. I am having a look now and think I've got a plan. For the time being, as you already know, please ignore it until I have fixed it.

**Comment by p3tecracknell** [comment]
I've implemented webroot, the way I see fit. Would you mind giving it a go? Unfortunately when you set the config (if you use the UI), it won't automatically change until you restart the python script. Note that if you modify config.ini manually, it will overwrite it when you stop the script, so update it whilst its not running if you modify it that way.

**Comment by DonOregano** [comment]
Excellent! I'll have a look at it tonight or tomorrow night!

**Comment by DonOregano** [comment]
Hi,

Sorry for not getting back to you before! But I have now finally given it a
whirl and it works beatifully!

Thanks a bundle!

/Lars
