### ISSUE TITLE
Call to SchedulerAPI as comment again

### ISSUE THREAD

**Issue by engelvinter** [p3tecracknell/tellprox#14]
SchedulerAPI was turned on in a commit.

However in merge of pull request it appears that the call is a comment again:
# SchedulerAPI(api, config)

Minor merge errro?

**Comment by p3tecracknell** [comment]
In my haste, I did not use branching correctly, which would have solved this problem. In essense, Scheduling is not finished and so I did not want it appearing in the API, so I commented it out until it is finished.
Thanks by the way for patch, its brilliant!

**Comment by engelvinter** [comment]
I see. Nice you liked my patch!

Have read your Trello page as well as having some minor idea.
Is there any tellprox discussion forum, somewhere - sadly it seems that github does not provide any?

**Comment by p3tecracknell** [comment]
I do not have a forum of any form at the moment. Can you suggest one that
is suitable?

**Comment by engelvinter** [comment]
Saw the following:
http://daveworth.github.io/2013/01/01/github-issues-as-a-discussion-forum-experiment.html

The jekyll project seem to have issue labels like: 'Discussion' and Suggestion'
https://github.com/jekyll/jekyll/issues?labels=Suggestion%2CDiscussion&page=1&state=open

Are you able to create more labels?

**Comment by p3tecracknell** [comment]
Certainly, looks good to me

**Comment by p3tecracknell** [comment]
The labels are created. Feel free to raise any 'issue' along with the necessary labels. The paradigm is slightly different in that I won't be trying to solve them like other issues, but it otherwise is a suitable solution
