### ISSUE TITLE
Minor updates needed in README

### ISSUE THREAD

**Issue by engelvinter** [p3tecracknell/tellprox#15]
Issue 1:
"$python setup.py install" should instead be "$sudo python setup.py install"
since default install path is /usr/local/lib/pythonX.Y/site-packages according to:
http://docs.python.org/2/install/

Issue 2:
"1. Change the validate_key value on line 30 of __ main **.py" should be removed since it is automatically set when doing install for the first time in __main**.py

**Comment by p3tecracknell** [comment]
I agree. I removed sudo as the instructions are then valid for Windows, though it does confuse matters. Long term, I want to produce detailed individual instructions for each OS.
