### ISSUE TITLE
Error when trying to acsess from chrome

### ISSUE THREAD

**Issue by ontrose** [p3tecracknell/tellprox#19]
Scheduler has no jobs to run
Bottle v0.11.6 server starting up (using CherryPyServer())...
Listening on http://192.168.1.7:7001/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "tellprox/bottle.py", line 764, in _handle
    return route.call(*_args)
  File "tellprox/bottle.py", line 1575, in wrapper
    rv = callback(_a, **ka)
  File "/home/pi/tellprox/tellprox/__main__.py", line 108, in wrapped
    return func(_args, *_kwargs)
  File "/home/pi/tellprox/tellprox/**main**.py", line 161, in devices
    return render_template('devices')
  File "/home/pi/tellprox/tellprox/**main**.py", line 123, in render_template
    return template(view, vars);
  File "tellprox/bottle.py", line 3117, in template
    return TEMPLATES[tplid].render(kwargs)
  File "tellprox/bottle.py", line 3090, in render
    self.execute(stdout, kwargs)
  File "tellprox/bottle.py", line 3078, in execute
    eval(self.co, env)
  File "tellprox/bottle.py", line 185, in **get**
    value = obj.**dict**[self.func.**name**] = self.func(obj)
  File "tellprox/bottle.py", line 2977, in co
    return compile(self.code, self.filename or '<string>', 'exec')
  File "/home/pi/tellprox/tellprox/views/devices.tpl", line 234
    globals()['_rebase']=(u"title='Devices',", dict(name='devices', **locals())))
                                                                                ^
SyntaxError: invalid syntax

**Comment by p3tecracknell** [comment]
I don't have access to my dev machine to look into this properly, but I
suspect this is because I use the latest version of Bottle (v0.12), so make
sure that is updated. I need to look into how I enforce  the use to upgrade
so this doesn't happen.

**Comment by ontrose** [comment]
Hey and tnx for a swift response. Since im a total newbie on linux and such i cant find how to update the bottle... did a sudo apt-get update and upgrade but still the old bottle.

I did find how to install a new version of the bottle tho it still starts with the old 0.11.6

**Comment by p3tecracknell** [comment]
No worries. The script in the root of my project 'setup.py' will fetch and install the necessary dependencies (including Bottle 0.12.5). Therefore if you run:
sudo python setup.py install
It should the necessary versions of everything. Please inform me if it works so I can close this down, otherwise we can look into this more.

**Comment by ontrose** [comment]
hey, i did what you wrote and it seamed to be fine but when i launch tellprox it still uses Bottle 0.11.6.
Im at a loss and have really no clue why and what to do. It still works like it should when i use my android phone with remotestick. So no harm but an error is an error =)

**Comment by p3tecracknell** [comment]
Maybe try uninstalling bottle?
pip uninstall bottle
To confirm, you could run Tellprox and see if it complains that it is missing.
If so, just run
sudo python setup.py install

**Comment by ontrose** [comment]
Hey I didn't find a solution of how to uninstall or get tellprox to use the newer version of bottle. So I did a new git pull to a new directory and then it works, so it's all good.
