### ISSUE TITLE
Sensors on Linux

### ISSUE THREAD

**Issue by lugiber** [p3tecracknell/tellprox#2]
Unfortunatly i have never got my sensors to work/show up on the telldus servers. They work just fine locally with TelldusCenter and tdtool.
There seems to be some features missing in the linux client/server that is available in windows.
Is there anything else you can think of that i might do to help?

Sorry, tried writing this in "enhancments". But i guess i messed up...

**Comment by p3tecracknell** [comment]
No worries, I will have to infer the layout using tdtool for the time being. If you could find the specification somehow, that would be great!

**Comment by lugiber** [comment]
I have just been in contact with the developer of remotestick (the android app) and he has shared his info with me.
Could you please send an email to me and i'll share the info there. (I don't want to make it public.)

In the meantime. Have you seen this?

http://developer.telldus.se/attachment/ticket/114/tdtool-with-sensors.py

**Comment by lugiber** [comment]
Just to confirm, you got my emails, right?

**Comment by p3tecracknell** [comment]
Yeah sorry I'm crazy busy at the moment

**Comment by lugiber** [comment]
No problems!
I sent the info through my mobile, and I'm not really certain how the Gmail
app works (i usually use k9)so i was afraid that I messed something up!
Just let me know when you've got something for me to test!

**Comment by p3tecracknell** [comment]
I have rewritten a lot of TellProx using Telldus-py as a submodule. I now have access to pythonic information including sensors, but lacking a sensor name. As I do not have a Tellstick-Net or any sensors, can you please tell me how you name them?
Based on the example data you sent me by e-mail I imagine that the name is stored by the core information.
Also, is there any indication of how 'ignore' works for sensors? It appears there is a REST method called setIgnore which you can set on any sensor. You can then get a list of all sensors and choose to request ignored ones. Do you know if that flag can be set any other way?

**Comment by p3tecracknell** [comment]
I have now checked in the latest codebase. It uses a forked version of telldus-py. If you get a chance could you test it please? The sensor name and ignore functionality has been skipped for the time being

**Comment by lugiber** [comment]
I'm on my way home from work at the moment. But I'll try it out and get
back to you within the hour.
Thanks!

**Comment by lugiber** [comment]
I have now had time to test it. I'm afraid something goes wrong. Something
goes wrong when i try to refresh the device list via my phone.
Hopefully the debug info tells you something!
Here goes:

Nexus-4 - - [06/May/2013 19:16:13] "GET
/json/devices/list?supportedMethods=1023 HTTP/1.1" 200 2293
Nexus-4 - - [06/May/2013 19:16:13] "GET /json/sensors/list HTTP/1.1" 200 934
Traceback (most recent call last):
  File "/home/peter/Desktop/tellprox-master/tellprox/bottle.py", line 764,
in _handle
    return route.call(*_args)
  File "/home/peter/Desktop/tellprox-master/tellprox/bottle.py", line 1575,
in wrapper
    rv = callback(_a, **ka)
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 39, in route_all
    elif (ftype == 'clients' and func == 'list'): resp =
self.route_clients()
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 115, in route_clients
    return { 'client': [get_client_info()] }
NameError: global name 'get_client_info' is not defined
Nexus-4 - - [06/May/2013 19:16:25] "GET /json/clients/list HTTP/1.1" 500 763

FYI Nexus-4 is what i have named my phone in the "hosts" file to get around
the reverse name lookup delays.
Let me know if you require additional info. I'm at home all night! :-)

/Peter

**Comment by lugiber** [comment]
Btw. If you want to see my sensors output live.
You can reach it at:

http://legion.kahn.nu:8084/json/sensors/list

Perhaps that makes things easier for you to debug!

/Peter

**Comment by p3tecracknell** [comment]
Hi

I checked in a fix last night. The problem with making so many changes and
not being able to run the code makes it quite hard!

Pete

**Comment by lugiber** [comment]
Hi!
And thanks for your efforts! I understand that it is very difficult to work
and debug without access to the hardware!

I downloaded the latests version and it crashes when i start it.
This is the error message i get:

python -m tellprox
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/peter/Desktop/tellprox-master/tellprox/__main__.py", line 8,
in <module>
    import tellstick_api
  File "tellprox/tellstick_api.py", line 104
    return TELLSTICK_SUCCESS
         ^

Hope this tells you something.
When i checked the json output of yesterdays version i noticed that the
formatting wasn't right. The sensor ids were there, but no sensor
information.
Unfortunatly i don't have that particular version of the code. So i can't
show you the specific output.
I will keep backups from now on!
And let me know if you need me to do something else!
If you'd like you can write to me at peter@kahn.nu. I check that email
adress more regularly than this one. But i really don't want to post that
adress on forums because of spam etc, thats why i gave you this adress in
the first place!

/Peter

**Comment by p3tecracknell** [comment]
Sorry, I tried to put the fix in too quickly. I've fixed _that_ bug

**Comment by lugiber** [comment]
No problems!
I have just tried the new version and i think we are getting somewhere!
The server runs stable and lists the switches. But it crashes when it gets
to the sensor info.

Debug output from server (nothing out of the ordinary)

c-6d20e555.010-118-73746f10.cust.bredbandsbolaget.se - - [07/May/2013
18:24:49] "GET /json/devices/list?supportedMethods=1023 HTTP/1.1" 200 2293
c-6d20e555.010-118-73746f10.cust.bredbandsbolaget.se - - [07/May/2013
18:24:49] "GET /json/sensors/list HTTP/1.1" 200 1065

When i list the info from "/json/sensors/list" i see this:

{"sensor": [{"ignored": 0, "name": "TODO", "editable": 1,
"lastUpdated": "TODO", "client": 1, "online": 1, "id": 0,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": "TODO", "client": 1, "online": 1, "id": 1,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": "TODO", "client": 1, "online": 1, "id": 7,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": "TODO", "client": 1, "online": 1, "id": 11,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": "TODO", "client": 1, "online": 1, "id": 12,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": "TODO", "client": 1, "online": 1, "id": 13,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": "TODO", "client": 1, "online": 1, "id": 14,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": "TODO", "client": 1, "online": 1, "id": 21,
"clientName": "TellProx"}]}

As you can see the sensors and ids are listed. But not the sensor values.
Something like this is what should be displayed (according to the writer of
the tellstick software)

{"id":"4488","clientName":"TellStick
Net","name":"Outdoors","lastUpdated":1367377137,"ignored":0,"editable":1,"data":[{"name":"temp","value":"0.6"},{"name":"humidity","value":"57"}],"protocol":"fineoffset","sensorId":"239","timezoneoffset":7200}

You probably already know this. But anyway...

Thanks a lot for your hard work!

/Peter

**Comment by p3tecracknell** [comment]
Hey, just to say that I am aware of the problem and have started looking
into it but don't have much time at the moment.

**Comment by lugiber** [comment]
Thanks for the info!
I understand fully that you have other things to do than this. I'm just
happy that you haven't given up on me!
Just let me know if there is anything I can do to ease things for you and
I'll be right on it!

Thanks again!
/Peter

**Comment by lugiber** [comment]
Oh, one more thing. I wasn't clear when I made the last bug report. I wrote
that "the program crashed" when getting the sensor info.
What i meant to say was that the client (remotestick) crashes, not your
server.
Hope things are crystal clear now!

/Peter

**Comment by p3tecracknell** [comment]
Hi,
I'm just putting together some changes, which I hope should now work. In the following example:
{"id":"4488","clientName":"TellStick Net","name":"Outdoors","lastUpdated":1367377137,"ignored":0,"editable":1,"data":[{"name":"temp","value":"0.6"},{"name":"humidity","value":"57"}],"protocol":"fineoffset","sensorId":"239","timezoneoffset":7200}
I've noticed there is an 'id' and 'sensorId'. Any idea what the sensorId is?

**Comment by p3tecracknell** [comment]
I have checked in the next step. It includes a mocked sensor 9999, which I use as I have no sensors. It should show all your sensors plus the 9999, which I will remove once I know it is working.
I will add the ignored functionality now

**Comment by lugiber** [comment]
Hi, and thanks for pursuing this!
I have no idea on the difference between the different sensor id:s. But at
least one of them should be the identification of the specific sensor. You
add a specific Id to the different sensors much in the same way that you
give your light switches different ids so that you can turn them on
individually. (Hope I'm making sense.)
If you have got something for me to try just let me know!
I'll be gone over the weekend, so I won't be able to test anything between
Friday and late Sunday.
But please keep me posted and let me know if you have any questions!

/Peter

**Comment by lugiber** [comment]
So, here's the debug output from the latest version.

The server starts alright. But when i connect the client (remotestick) i
get the message that the client could not connect to the server.
And the server produces the following debug output:

Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "/home/peter/Desktop/tellprox-master/tellprox/bottle.py", line 764,
in _handle
    return route.call(*_args)
  File "/home/peter/Desktop/tellprox-master/tellprox/bottle.py", line 1575,
in wrapper
    rv = callback(_a, **ka)
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 72, in route_all
    elif (ftype == 'clients' and func == 'list'): resp =
self.route_clients()
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 151, in route_clients
    return { 'client': [self.get_client_info()] }
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 257, in get_client_info
    'id': config['client_id'] or 1,
NameError: global name 'config' is not defined
Nexus-4 - - [23/May/2013 22:07:04] "GET /json/clients/list HTTP/1.1" 500 763

If i then refresh the client it lists all the light switches before
crashing. And the server outputs the same error message:

Nexus-4 - - [23/May/2013 22:09:38] "GET
/json/devices/list?supportedMethods=1023 HTTP/1.1" 200 2293
Nexus-4 - - [23/May/2013 22:09:38] "GET /json/sensors/list HTTP/1.1" 200
1915
Traceback (most recent call last):
  File "/home/peter/Desktop/tellprox-master/tellprox/bottle.py", line 764,
in _handle
    return route.call(*_args)
  File "/home/peter/Desktop/tellprox-master/tellprox/bottle.py", line 1575,
in wrapper
    rv = callback(_a, **ka)
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 72, in route_all
    elif (ftype == 'clients' and func == 'list'): resp =
self.route_clients()
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 151, in route_clients
    return { 'client': [self.get_client_info()] }
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 257, in get_client_info
    'id': config['client_id'] or 1,
NameError: global name 'config' is not defined
Nexus-4 - - [23/May/2013 22:09:46] "GET /json/clients/list HTTP/1.1" 500 763
Nexus-4 - - [23/May/2013 22:09:48] "GET /json/sensors/list HTTP/1.1" 200
1915
Nexus-4 - - [23/May/2013 22:09:49] "GET
/json/devices/list?supportedMethods=1023 HTTP/1.1" 200 2293

Hope this helps. And let me know if you need any other information!

Thanks!

/Peter

**Comment by p3tecracknell** [comment]
My apologies, that was a broken check-in. The development server doesn't
always use my latest code, so areas break and I don't realise for a few
minutes. I'll check in a fixed version shortly

**Comment by lugiber** [comment]
Nice! So there is still hope! :-)
Let me know when the latest version is up and I'll give it another go!

**Comment by p3tecracknell** [comment]
I have just checked in a fix. Fingers crossed it works!

**Comment by lugiber** [comment]
Hmm.
I'm not sure what could be wrong. I don't see any sensor information.
And the server debug output looks "normal" like this:

Nexus-4 - - [23/May/2013 22:42:46] "GET
/json/devices/list?supportedMethods=1023 HTTP/1.1" 200 2293
Nexus-4 - - [23/May/2013 22:42:46] "GET /json/sensors/list HTTP/1.1" 200 14

I can turn off and on lights as usual. But i see no sensors on my phone.

Please have a look at :

http://legion.kahn.nu:8084/

You should be able to see some information there (it's my live server).

Hope it helps!

/Peter

**Comment by p3tecracknell** [comment]
That is confusing. I have checked in an attempt at something. Would you mind trying that? If that does not work, then would you mind getting a copy of telldus-py (https://github.com/erijo/telldus-py) and seeing if the sensors show?

**Comment by lugiber** [comment]
I tried the latest version and the client crashed again.

This is the debug output:

Nexus-4 - - [23/May/2013 22:54:22] "GET
/json/devices/list?supportedMethods=1023 HTTP/1.1" 200 2293
Nexus-4 - - [23/May/2013 22:54:22] "GET /json/sensors/list HTTP/1.1" 200 2054
Traceback (most recent call last):
  File "/home/peter/Desktop/tellprox-master/tellprox/bottle.py", line
764, in _handle
    return route.call(*_args)
  File "/home/peter/Desktop/tellprox-master/tellprox/bottle.py", line
1575, in wrapper
    rv = callback(_a, **ka)
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 71, in route_all
    elif (ftype == 'clients' and func == 'list'): resp = self.route_clients()
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 150, in route_clients
    return { 'client': [self.get_client_info()] }
  File "/home/peter/Desktop/tellprox-master/tellprox/tellstick_api.py",
line 260, in get_client_info
    'id': config['client_id'] or 1,
NameError: global name 'config' is not defined
Nexus-4 - - [23/May/2013 22:54:32] "GET /json/clients/list HTTP/1.1" 500 763
Nexus-4 - - [23/May/2013 22:54:38] "GET
/json/devices/list?supportedMethods=1023 HTTP/1.1" 200 2293
Nexus-4 - - [23/May/2013 22:54:38] "GET /json/sensors/list HTTP/1.1" 200 2054

I'll have a look at telldus-py and get back to you soon!

/Peter

**Comment by p3tecracknell** [comment]
That was a bug in the clients info. That was the first time either of us
ran the code since I changed it! Note, I really need to write some unit
tests

**Comment by p3tecracknell** [comment]
(fix checked in)

**Comment by lugiber** [comment]
I ran td_sensors from telldus-py and that seems to work just fine!

This is the output i got:

./td_sensors
id: 21, protocol: mandolyn, model: temperaturehumidity
  @ Thu May 23 22:58:48 2013 | temperature: 12.5
  @ Thu May 23 22:58:48 2013 | humidity: 58

id: 14, protocol: mandolyn, model: temperaturehumidity
  @ Thu May 23 22:58:55 2013 | temperature: 21.2
  @ Thu May 23 22:58:55 2013 | humidity: 53

id: 12, protocol: mandolyn, model: temperaturehumidity
  @ Thu May 23 22:58:55 2013 | temperature: -26.8
  @ Thu May 23 22:58:55 2013 | humidity: 58

id: 13, protocol: mandolyn, model: temperaturehumidity
  @ Thu May 23 22:58:39 2013 | temperature: 28.2
  @ Thu May 23 22:58:39 2013 | humidity: 53

id: 11, protocol: mandolyn, model: temperaturehumidity
  @ Thu May 23 22:59:09 2013 | temperature: 3.7
  @ Thu May 23 22:59:09 2013 | humidity: 67

id: 32, protocol: fineoffset, model: temperaturehumidity
  @ Sun May 12 18:08:46 2013 | temperature: 0.0
  @ Sun May 12 18:08:46 2013 | humidity: 0

id: 1, protocol: fineoffset, model: temperaturehumidity
  @ Thu May 23 01:15:48 2013 | temperature: 0.0
  @ Thu May 23 01:15:48 2013 | humidity: 0

id: 0, protocol: fineoffset, model: temperaturehumidity
  @ Thu May 23 00:41:48 2013 | temperature: 0.0
  @ Thu May 23 00:41:48 2013 | humidity: 0

id: 3, protocol: fineoffset, model: temperaturehumidity
  @ Wed May 22 22:49:48 2013 | temperature: 0.0
  @ Wed May 22 22:49:48 2013 | humidity: 0

id: 2, protocol: fineoffset, model: temperaturehumidity
  @ Thu May 23 00:46:48 2013 | temperature: 0.0
  @ Thu May 23 00:46:48 2013 | humidity: 0

id: 255, protocol: fineoffset, model: temperature
  @ Thu May 16 11:22:45 2013 | temperature: -204.7

id: 7, protocol: fineoffset, model: temperaturehumidity
  @ Wed May 22 23:16:48 2013 | temperature: 0.0
  @ Wed May 22 23:16:48 2013 | humidity: 0

id: 31, protocol: fineoffset, model: temperaturehumidity
  @ Tue May 21 19:59:40 2013 | temperature: -0.0
  @ Tue May 21 19:59:40 2013 | humidity: 0

Found 13 sensor(s)

Hope that helps. But i guess it will just confuse you (as bugs often do).

/Peter

**Comment by p3tecracknell** [comment]
That is confusing as I have hard-coded two sensors in, which should in
addition to your sensors also give the output:

{"sensor": [{"ignored": 1, "name": "TODO", "editable": 1,
"lastUpdated": "timestamp", "client": 1, "online": 1, "id": 9999,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": "timestamp", "client": 1, "online": 1, "id": 9998,
"clientName": "TellProx"}]}

Are you sure it is using the latest code?

**Comment by lugiber** [comment]
I totally understand that this is incredibly hard for you! I just wish I
could be of more help!
All I can do is to test stuff for you. So just send me the code as soon as
you have something you want to try out!
I'm expecting this to take time. So don't feel the need to rush things!
I'm just very greatful that you are helping me with this!
/Peter

**Comment by lugiber** [comment]
I'll download again. Can't understand what could be wrong. I downloaded it
just a couple of seconds before trying out. And I have never downloaded it
before!

**Comment by lugiber** [comment]
Are you sure you updated telldus-py?
Git claims that the last update was ten days ago. (To readme.md).'

Anyway your "fake sensors" show up here:

http://legion.kahn.nu:8084/json/sensors/list

**Comment by lugiber** [comment]
I have to go to bed now. It's late and i have to return to my stable
tellprox server.

Here's the output from

http://legion.kahn.nu:8084/json/sensors/list

{"sensor": [{"ignored": 0, "name": "TODO", "editable": 1,
"lastUpdated": 1368374926, "client": 1, "online": 1, "id": 32,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369346815, "client": 1, "online": 1, "id": 1,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369262808, "client": 1, "online": 1, "id": 2,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369255788, "client": 1, "online": 1, "id": 3,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369347055, "client": 1, "online": 1, "id": 0,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369257408, "client": 1, "online": 1, "id": 7,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369347069, "client": 1, "online": 1, "id": 11,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369347055, "client": 1, "online": 1, "id": 12,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369347039, "client": 1, "online": 1, "id": 13,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369347055, "client": 1, "online": 1, "id": 14,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": "timestamp", "client": 1, "online": 1, "id": 9999,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": "timestamp", "client": 1, "online": 1, "id": 9998,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369347048, "client": 1, "online": 1, "id": 21,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1369159180, "client": 1, "online": 1, "id": 31,
"clientName": "TellProx"}, {"ignored": 0, "name": "TODO", "editable":
1, "lastUpdated": 1368696165, "client": 1, "online": 1, "id": 255,
"clientName": "TellProx"}]}

In case you should need it.

Thanks a lot for all your help.
And let me know if there is anything else i can do!

/Peter

**Comment by lugiber** [comment]
I took a look at the sensorinfo that Patrik provided from his tellstick-net
and it differs somewhat from the info we get from tellprox. For one thing
the tellprox server use some white spaces where the .net doesn't.

The tellstick-net output:

{"sensor":[{"id":"887826","name":null,"lastUpdated":1367377341,"ignored":0,"client":"2923","clientName":"TellStick
Net","online":0,"editable":1}

Tellprox output:

{"sensor": [{"ignored": 0, "name": "TODO", "editable": 1, "lastUpdated":
1368374926, "client": 1, "online": 1, "id": 32, "clientName": "TellProx"},

Well, there are quite a few differences as you can see. For one the order
things are provided in the list might have a huge impact. There may also be
a problem with all the sensors being named "TODO". Could you not name them
TODO+id, eg TODO32 in the case above. Also the client is consistently 2923
on his server while it is 1 on ours.
Well, you can see the differences yourself. :-)
Hope this helps!

/Peter

**Comment by p3tecracknell** [comment]
Fortunately we are nearly there! The output is in a format called JSON. If you change the config.ini setting 'pretty_print' to true, it should lay the information out in an easier to read format.  I have formatted the outputs (http://jsonformatter.curiousconcept.com/) to make it clearer:

{
   "sensor":[
      {
         "id":"887826",
         "name":null,
         "lastUpdated":1367377341,
         "ignored":0,
         "client":"2923",
         "clientName":"TellStick Net",
         "online":0,
         "editable":1
      }
}

{
   "sensor":[
      {
         "ignored":0,
         "name":"TODO",
         "editable":1,
         "lastUpdated":1368374926,
         "client":1,
         "online":1,
         "id":32,
         "clientName":"TellProx"
      }
   }
}

Within a dictionary (a grouping surrounded in {}), the order of the keys is not important, providing that the key matches the value:
{ 'key': 'value', 'key2': 'value2' }
is the same as 
{ 'key2': 'value2', 'key': 'value' }

Spacing is also ignored in JSON, including new lines. Patrik's app will, I'm sure be able to understand the output with or without the extra spacing.

Naming is an issue that I need to resolve. Patrik's example is useful in that I can see that a null name is returned. What I will do is return null for all sensors that do not have a name. I will then implement the setname method, which will save the name to TellProx, which I can then use in list and info.

Finally client and clientName are specific to the app that is returning the information. I use TellProx to allow whoever is using the information to know that it is using TellProx rather than Tellstick-Net. This means that if I add an extra feature, the consumer (for example Patrik's app) can see that the client is TellProx and use the new feature. They are configurable in config.ini though if you would like the clientid and clientname to match Tellstick Net.

I hope that helps!

**Comment by lugiber** [comment]
Ah, i see!
Thanks for the clarification!
In that case we are actually almost there! Great!
I but it would also be nice if the errors were just due to formatting as it
would be easy to fix (i suppose).

Keep up the good work!
And let me know as soon as you have something for me to test!

/Peter

**Comment by p3tecracknell** [comment]
What are the errors then? I assumed that as you sent over the output, that it was all working ok now.

**Comment by lugiber** [comment]
I'm afraid something is still not working. But i'm not sure why as the
client crashes and the server outputs nothing out of the ordinary.

This is the output from the server:

Listening on http://legion.kahn.nu:8084/
Hit Ctrl-C to quit.

c-6d20e555.010-118-73746f10.cust.bredbandsbolaget.se - - [24/May/2013
11:48:17] "GET /json/clients/list HTTP/1.1" 200 279
c-6d20e555.010-118-73746f10.cust.bredbandsbolaget.se - - [24/May/2013
11:48:18] "GET /json/devices/list?supportedMethods=1023 HTTP/1.1" 200 4376
c-6d20e555.010-118-73746f10.cust.bredbandsbolaget.se - - [24/May/2013
11:48:18] "GET /json/sensors/list HTTP/1.1" 200 3895

So all looks good from the server side.
Have you got any ideas?

**Comment by p3tecracknell** [comment]
Ok, what I will probably have to do then is connect to your server using
the android app on my phone. I'll connect my phone to my computer which
will show me the output from the app. Hopefully then I will be able to see
what the app does not like about the server. Can I point the app at
http://legion.kahn.nu:8084/ ?

**Comment by lugiber** [comment]
Sure go right ahead!
I have to leave work in 15 minutes and since i started the server remotely
i'm not sure how long it will run after that.

But ill go straight home and start the server again. So in about two hours
time you'll have the latest server running for the remainder of the weekend.

**Comment by lugiber** [comment]
Just wanted to say that i'm home and have started the server. I will keep
it running until at least sunday!
Also, i'm going to a festival over the weekend. So chances are that i'm not
very good at replying to emails because of the noise and all the beers.

/Peter

**Comment by p3tecracknell** [comment]
The problem was that my test sensors produced rubbish data. I've fixed the
data and also made it so that the test sensors (which I use as I don't have
any real ones) only show if the config setting 'debug' is set to True.

**Comment by p3tecracknell** [comment]
(fix checked in)

**Comment by lugiber** [comment]
Awesome!
I'll test it as soon as I get home!

**Comment by lugiber** [comment]
Hi!
I have finally managed to get home and try out the latest tellprox version.
Unfortunatly remotestick still keeps crashing. As usual i have no idea why,
but here are the debug output (which i guess will not tell you much).

{'house': 'C', 'unit': '1'}
{'house': 'C', 'unit': '3'}
{'house': 'C', 'unit': '4'}
{'house': 'C', 'unit': '5'}
{'house': 'C', 'unit': '6'}
{'house': '2100430', 'unit': '7'}
{'house': '2130430', 'unit': '8'}
{'house': '2130438', 'unit': '9'}
{'house': '2130438', 'unit': '10'}
{'house': '2130438', 'unit': '12'}
{'house': '2130438', 'unit': '13'}
{'house': '2130438', 'unit': '15'}
{'house': '2130438', 'unit': '16'}
{'house': '2130438', 'unit': '17'}
c-6d20e555.010-118-73746f10.cust.bredbandsbolaget.se - - [27/May/2013
09:01:04] "GET /json/devices/list?supportedMethods=1023 HTTP/1.1" 200 4376
c-6d20e555.010-118-73746f10.cust.bredbandsbolaget.se - - [27/May/2013
09:01:05] "GET /json/sensors/list HTTP/1.1" 200 3891
c-6d20e555.010-118-73746f10.cust.bredbandsbolaget.se - - [27/May/2013
09:01:05] "GET /json/sensor/info?id=11 HTTP/1.1" 200 439

Let me know if you have anything else for me to test!

/Peter

**Comment by p3tecracknell** [comment]
Ok, it looks as if I was still using 'TODO' where numbers were expected so
the app crashed. Unfortunately I cannot workout where to get the timezone
offset and sensor ID from. I have set the sensor ID to be the ID of the
sensor, which  does not match the other behaviour. As in to say, there is
an ID for every device (including sensors) and then sensors have an extra
ID.
TImezone offset I may just set in the config for the time being. I have
checked in the fix

**Comment by lugiber** [comment]
You did it!
Nice work! I'm really impressed!
Thanks a lot! This is so cool!

**Comment by p3tecracknell** [comment]
Closing
