### ISSUE TITLE
Webroot ProxyReverse

### ISSUE THREAD

**Issue by Sivend83** [p3tecracknell/tellprox#20]
Hello!

Have trouble getting the proxy pass in apache or tellprox to work. 
Configured tellprox using webroot (/tellprox) but gets 404 from bottle / cherrypy

Not found: '/ / devices' (webroot string is missing)

apache config for my site:
Proxy Pass / tellprox http://127.0.01:8080/
Pass Reverse proxy / tellprox http://127.0.0.1:8080/

Do not really understand where the problem is.
Have tried to debug the app but it looks ok.

Regads
Sivend

**Comment by p3tecracknell** [comment]
Hi

This still needs refining, so hopefully we'll get to the bottom of this.
I have just checked out the latest branch, run the install, followed by starting it up.
I then changed the config setting of webroot to 'mywebroot'.
I verified that I could hit all of the pages in a web browser, for example http://[ip]:8080/devices
I restarted the python script.
I verified that I could hit all of the pages in a web browser with the webroot, for example http://[ip]:8080/mywebroot/devices

Could you confirm you can do the same. You won't need to get latest I imagine. Remember that you need to restart the app for the webconfig changes to apply.

**Comment by Sivend83** [comment]
Hello!

When using apache2 proxy_module so you not to use webroot. Did some tests and found that adding slash after the proxy setting is enough to be able to solve the problem.

Proxy Pass /tellprox/ http://127.0.01:8080/
Pass Reverse Proxy /tellprox/ http://127.0.0.1:8080/

Shall test on my setup when I get home tonight.

regards
Sivend

**Comment by p3tecracknell** [comment]
Brilliant!
