### ISSUE TITLE
TellproxAPI undefined

### ISSUE THREAD

**Issue by Ste-RH** [p3tecracknell/tellprox#22]
Appreciate this project doesn’t seem to have a lot of life these days. But hope someone can help!

Trying to setup on Windows after nearly a decade of using on a raspberry pi setup. But getting tellprox undefined on the webpage console log. What am I missing? Feels like tellpdus-py, but I can’t find it anywhere despite having Telldus Center installed and various other Python tells modules.

Thanks!

**Comment by Ste-RH** [comment]
No matter. Very odd one. compiled.js in the static folder had become zero bytes?! Replaced with original and things seem to be loading on the page now!

**Comment by Ste-RH** [comment]
For anyone looking to fire up tellprox on a windows 11 setup using Python 2.7…here are the Python packages that got me up and running (selected are not Python packages)…

![image](https://github.com/user-attachments/assets/2e98a770-3dc8-404c-8b7f-1aabce06677f)

Closing this issue now!

**Comment by p3tecracknell** [comment]
Thank you Ste. Knowing there is someone using it, I'm keen to actively
support it
