### ISSUE TITLE
Can't run on Raspberry Pi

### ISSUE THREAD

**Issue by nesalkiN** [p3tecracknell/tellprox#3]
Hello,

I can't make this run on one of my Pi-boxes with telldus-core grabbed and compiled from source. tdtool (and all other stuff) works as it should.

python -m tellprox
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/test/tellprox/tellprox/__main__.py", line 11, in <module>
    from tellstick import TellstickAPI
  File "tellprox/tellstick.py", line 2, in <module>
    from telldus.constants import *
ImportError: No module named telldus.constants

This Pi is running the latest official Debian Weezy image. All updates installed.

What have I missed?

**Comment by p3tecracknell** [comment]
Hi

I am happy to see someone else (trying) to use the software!
telldus.constants is part of telldus-py which is erijo's Python library for
Telldus. I am fairly new to github so there is a chance I have not got the
module referencing correct. Your file structure following a 'get' should be:

/tellprox
--static
--tellprox
--views
--telldus-py

Inside telldus-py should be a folder named telldus which contains
constants.py. If constants.py is there then I imagine it is to do with
where/how python looks for modules, in which case I am not too sure as I am
also fairly new to python!

Pete

**Comment by nesalkiN** [comment]
I use RemoteStick togheter with tasker. Tellstick does not have Tellstick Live support for headless servers.
When i switched to my rpi I needed a new solution to keep using RemoteStick and tasker...

-telldus-py, this folder is empty.
-tellprox has the following files: api.py  bottle_helpers.py  bottle.py  config.py  **init**.py  **main**.py  msensor.py  tasensor.py  tellstick.py

It think that something goes wrong when I do git clone git://github.com/p3tecracknell/tellprox.git ?

**Comment by p3tecracknell** [comment]
Ok, so you'll need to get the telldus-py source and place it in that
folder. That should solve that problem I hope

**Comment by nesalkiN** [comment]
I pulled telldus-py from you and did python setup.py install
And it worked.. but now:
"Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/test/tellprox/tellprox/__main__.py", line 14, in <module>
    from configobj import ConfigObj
ImportError: No module named configobj"

Edit:
Ok! Had som packages for python missing! I will add them here soon

**Comment by p3tecracknell** [comment]
That is an external dependency. My apologies, I haven't updated the
installation instructions. You will need to install it. I use pip

**Comment by nesalkiN** [comment]
I don't know if it works.
I am at work and the port is not open in the router but yeah:

"root@PiServer:/home/pi/test/tellprox# python -m tellprox
Bottle v0.11.6 server starting up (using CherryPyServer())...
Listening on http://127.0.0.1:8084/
Hit Ctrl-C to quit."

I had to add these packages to make it run:
python-cherrypy3
python-bottle
python-oauth
python-configobj
git (if you don't have it jet)

python-oauth may not be required but tdtool.py wants it.

This is what i did (I already had git but I will include it for others):
**cd ~
sudo apt-get install python-cherrypy3 python-bottle python-oauth python-configobj git
git clone --recursive git://github.com/p3tecracknell/tellprox.git
cd tellprox/telldus-py/
sudo python setup.py install
cd ..
sudo python -m tellprox**

Don't forget to edit config.ini.

Good for other people to know! :)

Thank you for your help Pete! I think this can be popular for all the people with Raspberry Pi's and Tellstick..

Edit: It works! Just having one blank unit. I see 14 but I have 13. 1 blank. Could be something in Remotestick.

**Comment by p3tecracknell** [comment]
Thank you, I just updated the readme with the instructions you provided. Following a quick google, it looks like one should be able to:
git clone --recursive git://github.com/p3tecracknell/tellprox.git
So there is only one git command needed. If you have a spare second, would you mind checking? This should simplify the process, especially if I use any other submodules.

**Comment by nesalkiN** [comment]
I got everything with that command but i still had to install telldus-py.

pi@PiServer ~/tellprox/telldus-py $ ls
bin  LICENSE.txt  README.md  run_tests  setup.py  telldus  test

You also need a space between cd and ~. :) "cd ~"

I changed my instructions.

**Comment by p3tecracknell** [comment]
I understand, thank you. I have copied your latest instructions verbatim to the read me. I do not have a raspberry pi, so cannot test, but if it is to be useful to the raspberry pi community, is it worth linking to any documentation, such as what you used to compile telldus-core or is it already well documented?

**Comment by nesalkiN** [comment]
For telldus-core:

sudo nano /etc/apt/sources.list.d/telldus.list
Add this line:
deb-src http://download.telldus.com/debian/ stable main
Save and exit (ctrl+x, followed by Y for yes or equivalent in your language)

wget http://download.telldus.se/debian/telldus-public.key && sudo apt-key add telldus-public.key
sudo apt-get update
sudo apt-get install build-essential cmake libconfuse-dev libftdi-dev help2man
sudo apt-get build-dep telldus-core
mkdir ~/telldus-temp
cd ~/telldus-temp
sudo apt-get -b source telldus-core (This will take some time. "Take a fika" as we say in Sweden!)
sudo dpkg --install *.deb
cd .. 
sudo rm -r ~/telldus-temp

I already had my tellstick.conf from another Linux-system so I just made a copy to /etc/tellstick.conf.
If you don't have one, look here: http://developer.telldus.com/wiki/TellStick_conf

Run "man tdtool" to see how you can use tdtool.

:)

I have updated some stuff in the tellprox instructions too.

**Comment by p3tecracknell** [comment]
Brilliant, thank you!
