### ISSUE TITLE
tdtool and ascii characters

### ISSUE THREAD

**Issue by lugiber** [p3tecracknell/tellprox#5]
I decided to try the latest git version of your tellprox server and i immediatly ran into trouble.
I followed the instructions in the readme.md and installed the telldus.py without problems.
The tellprox server starts alright too. But when i try to refresh my devices i get the following error message:

<LocalRequest: GET http://example.com:8084/json/devices/list?supportedMethods=1023>
Traceback (most recent call last):
  File "/home/peter/Desktop/tellprox/tellprox/bottle.py", line 764, in _handle
    return route.call(*_args)
  File "/home/peter/Desktop/tellprox/tellprox/bottle.py", line 1575, in wrapper
    rv = callback(_a, **ka)
  File "/home/peter/Desktop/tellprox/tellprox/api.py", line 19, in route_all
    resp = self.callbacks[ftype](func)
  File "/home/peter/Desktop/tellprox/tellprox/tellstick.py", line 56, in route_devices
    for k, device in self.devices.iteritems()
  File "/home/peter/Desktop/tellprox/tellprox/tellstick.py", line 203, in device_to_dict
    'name':       device.name,
  File "/usr/local/lib/python2.7/dist-packages/telldus/telldus.py", line 217, in __getattr__
    return func(self.id)
  File "/usr/local/lib/python2.7/dist-packages/telldus/library.py", line 145, in free_string
    string = string.decode(Library.STRING_ENCODING)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
<LocalRequest: GET http://example.com:8084/json/sensors/list>
<LocalRequest: GET http://example.com:8084/json/sensor/info?id=11>
<LocalRequest: GET http://example.com:8084/json/sensor/info?id=13>
<LocalRequest: GET http://example.com:8084/json/sensor/info?id=12>
<LocalRequest: GET http://example.com:8084/json/sensor/info?id=21>
<LocalRequest: GET http://example.comu:8084/json/sensor/info?id=9999>
<LocalRequest: GET http://example.com:8084/json/sensor/info?id=9998>
<LocalRequest: GET http://example.com:8084/json/sensor/info?id=14>

As you see the sensors work just fine. But the light switches causes the errors and doesn't show on either Remotestick or via the browser.
Unfortunatly this also makes my backed up copy of tellprox crash. So i guess something goes wrong when i install telldus-py. (Install log pasted below.)

Have you got any ideas?

If you would like me to register this on github i'd be happy to do it!

Thanks!

/Peter

sudo python setup.py install
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/telldus
copying telldus/constants.py -> build/lib.linux-x86_64-2.7/telldus
copying telldus/telldus.py -> build/lib.linux-x86_64-2.7/telldus
copying telldus/library.py -> build/lib.linux-x86_64-2.7/telldus
copying telldus/**init**.py -> build/lib.linux-x86_64-2.7/telldus
running install_lib
copying build/lib.linux-x86_64-2.7/telldus/constants.py -> /usr/local/lib/python2.7/dist-packages/telldus
copying build/lib.linux-x86_64-2.7/telldus/telldus.py -> /usr/local/lib/python2.7/dist-packages/telldus
copying build/lib.linux-x86_64-2.7/telldus/library.py -> /usr/local/lib/python2.7/dist-packages/telldus
copying build/lib.linux-x86_64-2.7/telldus/**init**.py -> /usr/local/lib/python2.7/dist-packages/telldus
byte-compiling /usr/local/lib/python2.7/dist-packages/telldus/constants.py to constants.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/telldus/telldus.py to telldus.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/telldus/library.py to library.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/telldus/**init**.py to **init**.pyc
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/py_telldus-0.1.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/py_telldus-0.1.0.egg-info

**Comment by mangecc** [comment]
I also ran in to this problem, but running on windows 7.

What I dit was to edit the file telldus-py\telldus\library.py and change the ascii to utf-8 on line 55. installed it again and now it works

**Comment by lugiber** [comment]
You are a genious! It worked! Thanks!
I have my tdtool.py installed so i had to change:
/usr/local/lib/python2.7/dist-packages/telldus/library.py

Does any modern os even use ascii anymore?

**Comment by p3tecracknell** [comment]
Brilliant. Would you like to propose a patch to the author of telldus-py?
If not, I can fork the project and change it so that my (recursive) package
is ready. I would prefer to always reference his project as his code is
otherwise extremely good and I would like to always receive his updates

**Comment by lugiber** [comment]
I'll send him/her an email about the problem and it's solution. 
I guess it would be easier for you not to fork.
Now to a little O.T, do you have any plans on supporting password protection?

**Comment by p3tecracknell** [comment]
Thanks.
Authentication is next. I've locked my one down using apache for the time
being. Will be user and password for ui and API key for the API

**Comment by erijo** [comment]
Fixed in 5c1ca13c794ad0641b5b85d37c1b4850ea77867e in telldus-py. Please upgrade the submodule to fix this issue.
