### ISSUE TITLE
Cant get it to work on windows 7 64bit

### ISSUE THREAD

**Issue by mangecc** [p3tecracknell/tellprox#6]
Hi

Im fairly new to this whole python thing, and I cant seem to get it to work om my windows 7 machine.

I have installed python 2,7 for windows, and downloadet both the tellprox git and the telldus-py. My folder structer is:

tellprox
 -static
 -telldus-py
------bin
------telldus
------test
 -tellprox
 -views

When i run python -m tellprox i get:

C:\tellprox>python -m tellprox
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\tellprox\tellprox__main__.py", line 11, in <module>
    from tellstick import TellstickAPI
  File "tellprox\tellstick.py", line 2, in <module>
    from telldus.constants import *
ImportError: No module named telldus.constants

so it seems it cant find the module telldus.constants

If i move all files from C:\tellprox\telldus-py\telldus to C:\tellprox i get the following:

C:\tellprox>python -m tellprox
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\tellprox\tellprox__main__.py", line 11, in <module>
    from tellstick import TellstickAPI
  File "tellprox\tellstick.py", line 2, in <module>
    from telldus.constants import *
  File "telldus.py", line 24, in <module>
    from .constants import *
ValueError: Attempted relative import in non-package

So now Ive run out of idees. Any help would be appreciated, i thought it would be easy to get this working on windows but maybe I was wrong :)

**Comment by p3tecracknell** [comment]
I think you need to setup the telldus-py module.
CD to the telldus-py folder and run
python setup.py install
My apologies, that needs to go in the Windows instructions to match Linux.

**Comment by mangecc** [comment]
Ah thanks alot.

I also had to install 2 packages afterwords to get it to run, configocj and CherryPy but I managed to fix that with a little help from google :)

**Comment by p3tecracknell** [comment]
Mowglii, would you mind listing the extra tasks that you ran in order to get it installed on Windows? I have it installed on Windows locally, but cannot remember the exact tasks.  Did you use pip to install the packages?
I imagine it would be:
pip install configobj cherrypy
cd telldus-py
python setup.py install

**Comment by mangecc** [comment]
Well, I just downloaded the sources from https://pypi.python.org and ran the setup files.. sounds alot easier with pip thou :)

These 2 I used:
https://pypi.python.org/pypi/CherryPy/3.2.4
https://pypi.python.org/pypi/configobj

**Comment by p3tecracknell** [comment]
Brilliant thanks

**Comment by mangecc** [comment]
And also, I had to edit one file on telldus-py to get i to work, as I mentioned in the other open issue
