### ISSUE TITLE
xml output not working?

### ISSUE THREAD

**Issue by engelvinter** [p3tecracknell/tellprox#9]
Checked out the latest from git => Date:   Thu Jul 4 23:47:43 2013 +0100 'Validate config and cleaned up config front-end'

Trying to use the browser and the API function to receive xml answers.

If using devices/list and xml, all I get as an answer is '[object Document]'. See attached image.
On the other hand if using the same command and json, I get a full answer including all my defined switches.

![xml](https://f.cloud.github.com/assets/5185518/928096/2b2fc332-ffad-11e2-9e71-0ebc79990c81.png)

**Comment by p3tecracknell** [comment]
It is essentially working but does not render correctly on the API viewer. If you click Get or examine the response in something like Chrome you will see the XML output.
I will look into getting it to render correctly in the API viewer when I get a chance.

Thanks for raising the problem

**Comment by engelvinter** [comment]
You are right about rendering.
I tried it out with curl and I received xml output:

> curl http://localhost:8080/xml/devices/list

"<?xml version="1.0" ?>
<devices>
  <device client="1" clientName="TellProx" editable="0" id="1" methods="0" name="wallswitch 1" online="1" state="2" statevalue="0" type="device"/>
  <device client="1" clientName="TellProx" editable="0" id="2" methods="0" name="wallswitch 2" online="1" state="2" statevalue="0" type="device"/>
  <device client="1" clientName="TellProx" editable="0" id="3" methods="0" name="wallswitch 3" online="1" state="2" statevalue="0" type="device"/>
  <device client="1" clientName="TellProx" editable="0" id="4" methods="0" name="roofswitch 1" online="1" state="2" statevalue="0" type="device"/>
  <device client="1" clientName="TellProx" editable="0" id="5" methods="0" name="roofswitch 2" online="1" state="2" statevalue="0" type="device"/>
  <device client="1" clientName="TellProx" editable="0" id="6" methods="0" name="roofswitch 3" online="1" state="2" statevalue="0" type="device"/>
  <device client="1" clientName="TellProx" editable="0" id="7" methods="0" name="roofswitch 4" online="1" state="2" statevalue="0" type="device"/>
</devices>"
